version: "3"
services:
    app:
        build:
            context: images/nginx/1.18
            args:
                UID: "${_UID:-1000}"
                GID: "${_GID:-1000}"
        ports:
            - "${FORWARD_HTTPS_PORT:-4443}:443"
            - "${FORWARD_HTTP_PORT:-8080}:80"
        depends_on:
            - db
            - phpfpm
        volumes: &appvolumes
            - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
            - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
            - appdata:/var/www/html
            - ssldata:/etc/nginx/certs

    phpfpm:
        build:
            context: images/php/7.4
            args: 
                UID: "${_UID:-1000}"
                GID: "${_GID:-1000}"
                XDEBUG_PORT: "${FORWARD_XDEBUG_PORT:-9003}"
                XDEBUG_VERSION: "${XDEBUG_VERSION:--3.1.5}"
        depends_on:
            - db
        volumes: *appvolumes
        extra_hosts: # linuxonly
            - "host.docker.internal:host-gateway" # linuxonly

    db:
        image: mysql:8.0
        env_file:
            - env/db.env
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        command: "--default-authentication-plugin=mysql_native_password"

    # db:
    #     image: mariadb:10.5.12
    #     command:
    #         --max_allowed_packet=64M
    #         --optimizer_use_condition_selectivity=1
    #         --optimizer_switch="rowid_filter=off"
    #         --default-authentication-plugin=mysql_native_password
    #     ports:
    #         - "${FORWARD_DB_PORT:-3306}:3306"
    #     env_file: 
    #         - env/db.env
    #     volumes:
    #         - dbdata:/var/lib/mysqlb

volumes:
    dbdata:
    ssldata:
    appdata:
